#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/lumise'

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  Lumise::CLI.start
rescue Lumise::CLI::Error => e
  puts "ERROR: #{e.message}"
  exit 1
end
